let mydate = new Date()
// console.log(mydate.toString())
// console.log(mydate.toDateString())
// console.log(mydate.toLocaleString())
// console.log(mydate.toLocaleDateString())
// console.log(mydate.toLocaleTimeString())
// console.log(mydate.toJSON())
console.log(mydate.getMonth()+1)
console.log(mydate.getDay()+1)
console.log(mydate.getDate()+1)

// let mycreatedate = new Date (2023,0,23)
// console.log(mycreatedate)

// let mycreatedate = new Date (2023,0,23,5,3)
// console.log(mycreatedate.toLocaleString())
